export interface ContentPage {
  _id: string;
  title: string;              // Page title (e.g. "ABOUT US")
  slug: string;               // URL-friendly route slug (e.g. "about-us")
  content: string;            // HTML content string generated by TipTap editor

  // ─── Hero Visual & Media ──────────────────────────────
  heroBgImage?: string;       // Hero background photo URL (also video poster fallback)
  heroVideo?: string;         // Optional ambient background loop video URL (.mp4 / .webm)
  tagline?: string;           // Subtitle/tagline rendered below hero title

  // ─── Backward-Compatible Aliases ─────────────────────
  subtitle?: string;          // Alias of tagline
  heroImage?: string;         // Alias of heroBgImage
  bgMediaUrl?: string;        // Alias of heroBgImage
  videoUrl?: string;          // Alias of heroVideo

  // ─── SEO Metadata ────────────────────────────────────
  excerpt?: string;           // Short summary / open graph description
  metaTitle?: string;         // Document <title> tag
  metaDescription?: string;   // Meta description tag
  isActive: boolean;
  createdAt?: string;
  updatedAt?: string;
}

export interface ContentPagesResponse {
  pages: ContentPage[];
}
